 
[development]
address = "localhost"
port = 8000
log = "normal"
template_dir = "./website/templates/"
secret_key = "AOSqISFLJ55Vw36Jn1nrvXHqRpJsJoDvoGzYcpX7fFY="

[production]
address = "localhost"
port = 8000
log = "critical"
template_dir = "./website/templates/"