[package]
name = "bit"
version = "0.1.1"
authors = ["Peter Mezei <mezeipetister@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "*"
num-format = "*"
serde_json = "*"
serde_derive = "*"
serde = { version = "*", features = ["derive"] }
csv = "*"
open = "*"
bit_core = { path="../bit_core" }