name = "Gardenzilla könyvelés"
description = ".."
year = 2021
country = "HUN"
currency = "HUF"

[dependencies]
accounts = "accounts.bit"
balance_sheet = "balance.bit"
profit_loss = "profit.bit"
logs = "logs"